import { StyleSheet } from "@react-pdf/renderer";

/** Brand primary (purple/blue) — matches CRM design tokens */
const primary = {
  main: "#5b21b6",
  light: "#ede9fe",
  border: "#c4b5fd",
};

export const documentStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  logo: { fontSize: 18, fontWeight: "bold", color: "#1f2937" },
  docTitle: { fontSize: 18, fontWeight: "bold", marginBottom: 4, color: primary.main },
  docMeta: { fontSize: 9, color: "#6b7280" },
  billingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
    gap: 16,
  },
  billingBlock: {
    width: "48%",
    padding: 12,
    backgroundColor: primary.light,
    borderWidth: 1,
    borderColor: primary.border,
  },
  billingLabel: {
    fontSize: 8,
    color: "#6b7280",
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  billingText: { fontSize: 10, marginBottom: 2, color: "#1f2937" },
  table: { marginTop: 12, marginBottom: 12 },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    paddingVertical: 8,
  },
  tableRowAlt: {
    backgroundColor: "#f9fafb",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: primary.main,
    paddingVertical: 8,
    paddingHorizontal: 6,
  },
  colIndex: { width: "6%" },
  colItem: { width: "32%" },
  colQty: { width: "10%" },
  colUnit: { width: "10%" },
  colRate: { width: "12%" },
  colGst: { width: "10%" },
  colAmount: { width: "12%" },
  right: { textAlign: "right" },
  headerText: { color: "#ffffff", fontWeight: "bold", fontSize: 9 },
  totals: { marginTop: 12, marginLeft: "auto", width: "42%" },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
    fontSize: 10,
  },
  grandTotal: {
    fontWeight: "bold",
    fontSize: 12,
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#d1d5db",
  },
  words: { marginTop: 14, padding: 10, backgroundColor: "#f9fafb", fontSize: 9 },
  bankSection: {
    marginTop: 20,
    padding: 12,
    backgroundColor: primary.light,
    borderWidth: 1,
    borderColor: primary.border,
  },
  bankTitle: {
    fontSize: 9,
    fontWeight: "bold",
    marginBottom: 8,
    color: primary.main,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  bankRow: { flexDirection: "row", marginBottom: 4, fontSize: 9 },
  bankLabel: { width: "40%", color: "#6b7280" },
  bankValue: { width: "60%", fontWeight: "bold" },
  footer: { marginTop: 16, fontSize: 9, color: "#6b7280" },
  watermark: {
    position: "absolute",
    top: "40%",
    left: 0,
    right: 0,
    textAlign: "center",
    fontSize: 48,
    color: "rgba(0,0,0,0.08)",
    fontFamily: "Helvetica-Bold",
  },
});
